# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e5a95d8165a4b60e3ed50d346f1de5617939b6c8da50a60dc678986d22377e00e63b865b379af8b8e421dce60425f47427dc226d50df729d2e48f5ab553cb86

test:
  secret_key_base: 2bc46a03647d6de9ddf4d71bfd03f4264e0c3f21f305901b05e8483455766c99f6a59a38115d3a1a8f5557649b1f00e17124ca04f7deba7a340db6b06b3fcc95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
